### ISSUE TITLE
THUMOS14 dataset dataset files for Diagnosing Error

### ISSUE THREAD

**Issue by HYPJUDY** [HumamAlwassel/DETAD#1]
Hi~ In the README you mentioned "We provide augmented dataset files for the ActivityNet v1.3 (validation) and THUMOS14 dataset in the data folder. " but I cannot find files related to THUMOS14. Since I am doing experiments on THUMOS14 and it will be of great help to me to diagnose error for my results, could you please share the files related to THUMOS14 dataset?

**Comment by HumamAlwassel** [comment]
Thanks for your interest in our DETAD work. You can find the THUMOS14 files in https://github.com/HumamAlwassel/DETAD/tree/master/data

Cheers!
