### ISSUE TITLE
[Bug] Missing order in false_positive_analysis.py

### ISSUE THREAD

**Issue by tzzcl** [HumamAlwassel/DETAD#10]
Hello, Thank you for your useful tools!

But I find that, when you upgrade your code from Python2 to Python3, you missed some code in false_positive_analysis.py, which will result in wrong error type order:

https://github.com/HumamAlwassel/DETAD/commit/def334f6cd385aff860adfb7bbe9db8d3b2c3ec2#diff-00dcae1f1ee99cb43ee648309d01c68705cb589f0177073fb6995cce721568adL152-L154

It results in wrong results on THUMOS14.

Could you verify that bug?

**Comment by HumamAlwassel** [comment]
Hello @tzzcl,

Thank you for your interest in our work. 
The line you refer to is deleted on purpose to allow the correct order when switching to python 3. The resulting output of the code is correct. Can you make sure that we are able to reproduce the same output of the example shared on the repo? you should be able to attain the same output using the updated conda env.

Let me know (by replying on this issue) if you are still having problems. 

Cheers,
Humam

**Comment by tzzcl** [comment]
Hello, Thank you for your quick reply!

I'm experiencing this issue when I'm using a prediction on THUMOS14 dataset, not the provided ActivityNet examples. I can also get correct results on the provided examples.

Maybe there are some issues there?

Regards,
Chenlin

**Comment by HumamAlwassel** [comment]
Hello Chenlin,

Thanks for clarifying. 
You are indeed right - I was able to reproduce the bug on my side for THUMOS14. 

I just made the fix with the most recent commit. I also added a sample output for a method on the THUMOS14 testing subset. 
Please make sure that you can reproduce the same sample output if you still have issues. 

Cheers!
