### ISSUE TITLE
I got thumos14 weight file.pth.tar,how could i convert the pth.tar file to .json, like ur provide CMS-RC3D_predictions_on_thumos14_testing_subset.json

### ISSUE THREAD

**Issue by blank-Cd** [HumamAlwassel/DETAD#12]
i use the actionformer :https://github.com/happyharrycn/actionformer_release, and got epoch_0.40.pth.tar, how can i get the predict result just like u provide CMS-RC3D_predictions_on_thumos14_testing_subset.json, so i can diagnose error type in Temporal Action Detection. 
thank for u  @HumamAlwassel

**Comment by escorciav** [comment]
Just go through the Python code & tailor it yourself. Good luck!

Feel free to re-open or wait for the wizard @HumamAlwassel 🧙 . He's a baby these days. Family kills research (more likely for ppl in industry than academia) 😄

**Comment by blank-Cd** [comment]
Mark as resolved.
