### ISSUE TITLE
API = 'http://ec2-52-11-11-89.us-west-2.compute.amazonaws.com/challenge17/api.py' 

### ISSUE THREAD

**Issue by hw-liang** [HumamAlwassel/DETAD#5]
Traceback (most recent call last):                                                                                                                                                       File "false_positive_analysis.py", line 244, in <module>                                                                                                                             
    main(args.ground_truth_filename, args.subset, args.prediction_filename, args.output_folder, args.is_thumos14)                                                                       │
  File "false_positive_analysis.py", line 218, in main                                                                                                                                  
    minimum_normalized_precision_threshold_for_detection=0.0                                                                                                                             File "/home/Documents/DETAD-master/src/action_detector_diagnosis.py", line 59, in __init__                                                                                            self.blocked_videos = get_blocked_videos()                                                                                                                                          File "/home/Documents/DETAD-master/src/utils.py", line 20, in get_blocked_videos                                                                                                      response = urlopen(req)                                                                                                                                                             File "/opt/conda/lib/python3.7/urllib/request.py", line 222, in urlopen                                                                                                               return opener.open(url, data, timeout)                                                                                                                                              File "/opt/conda/lib/python3.7/urllib/request.py", line 531, in open                                                                                                                  response = meth(req, response)                                                                                                                                                      File "/opt/conda/lib/python3.7/urllib/request.py", line 641, in http_response                                                                                                          'http', request, response, code, msg, hdrs)                                                                                                                                         File "/opt/conda/lib/python3.7/urllib/request.py", line 569, in error                                                                                                                  return self._call_chain(*args)                                                                                                                                                      File "/opt/conda/lib/python3.7/urllib/request.py", line 503, in _call_chain                                                                                                           result = func(*args)                                                                                                                                                                File "/opt/conda/lib/python3.7/urllib/request.py", line 649, in http_error_default                                                                                                     raise HTTPError(req.full_url, code, msg, hdrs, fp)                                                                                                                                  urllib.error.HTTPError: HTTP Error 502: badgateway

**Comment by hw-liang** [comment]
Hi, I tried to use your code for analysis. However, the API you provide for function "get_blocked_videos" does not work well. This website is unreachable. Could you give any solution?

Thank you

**Comment by HumamAlwassel** [comment]
Hi Hanwen,

Thanks for your interest in our work. This API is used for the ActivityNet challenge to keep track of the list of the ActivityNet videos that are no longer available on Youtube (e.g. removed by the user). The API is used for the challenge-only to limit the evaluation to those testing videos available on YouTube. 

For the purposes of DETAD, you can ignore the call to this API and instead run the diagnostic tool on the full list of videos. To do so, you can set the variable `check_status` to `False` in L214.
https://github.com/HumamAlwassel/DETAD/blob/4af0c19e607c6a1da97cb8a688b2d77095781a1a/src/false_postive_analysis.py#L214

Cheers!
